### ISSUE TITLE
Extraction of tables

### ISSUE THREAD

**Issue by joe-getcouragenow** [grisha/hbshape#1]
Do you know if it would be possible to extract out the tables via your cgo library ?

Then the call to hb_shape could possibly be written in golang to use those tables and so we no longer have the baggage of s cgo dependency.

For context on where this is being discussed go here : 

https://todo.sr.ht/~eliasnaur/gio/146

And the project in general: 

https://gioui.org/

**Comment by grisha** [comment]
It's been a while and I can't remember the details now, so I might be wrong, but I think the particular info within tables is somehow so convoluted that delegating it all to the C lib is an easier option, or else you'll end up re-implementing that stuff in Go, which would be fantastic, but a lot of work. Sorry this comment is neither here nor there :|

**Comment by joe-getcouragenow** [comment]
hey @grisha Thank you for the reply.

Yeah i get what you mean. Its makes sense what your saying.
I think i got the info i needed to make a decision or at least part of he decision matrix. The Table structure is complex as hell :)

SO I am closing this issue . 

Watch the gio Repo / List for updates to see what happens with this idea...
